spring:
  application:
    name: my-order-service
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb:localhost:3306:mydb;DB_CLOSE_DELAY=-1;
#    username: root
#    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  level:
    org.springframework.security: DEBUG
