plugins {
    id 'java'
    id 'java-library'
    id 'org.springframework.boot' version '2.5.7'
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'org.springframework.boot'
}

allprojects {
    apply from: "$rootProject.projectDir/dependencies.gradle"

    group = 'org.nemo'
    version = '1.0'

    java.sourceCompatibility = JavaVersion.VERSION_17

    java{
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    configurations{
        compileOnly.extendsFrom annotationProcessor
        testCompileOnly.extendsFrom testAnnotationProcessor
        testAnnotationProcessor.extendsFrom annotationProcessor
    }

    repositories {
        mavenCentral()
    }



    dependencies {
        compileOnly libs.lombok
        annotationProcessor libs.lombok

        implementation libs.guava

        testImplementation libsTest.junitJupiterApi
        testRuntimeOnly libsTest.junitJupiterEngine
    }

    test {
        useJUnitPlatform()
    }

    tasks.register('hello') {
        doLast {
            println "I'm ${project.name}!"
        }
    }
}



