
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/native-file-repo
        git: # default
#          uri: file:///Users/yonghwankim/Documents/git-local-repo
          uri: https://github.com/joneconsulting/spring-cloud-config
          default-label: master
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
