
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/native-file-repo
        git: # default
          uri: https://github.com/yonghwankim-dev/spring-cloud-config.git
          default-label: master
  profiles:
    active: native
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
