spring:
  application:
    name: my-catalog-service
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: h2
    defer-datasource-initialization: true
server:
  port: 0
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
logging:
  level:
    com.example.catalogservice: DEBUG
