server:
  port: 0
spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: $2a$10$rpeTmpDTs6ukQ0k4YkROKuGX4ireRSd8M/XhbnbrH6qfBqne3dSVy
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

greeting:
  message: Welcome to the Simple E-commerce. (spring boot)

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
          - beans
          - httptrace
          - busrefresh
          - prometheus
          - metrics
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
logging:
  level:
    com.example.userservice.client: DEBUG
